// Code generated by sdkcodegen; DO NOT EDIT.

package service

// execTbkItemInfoGet 淘宝客商品详情查询（简版）
func (s *Service) execTbkItemInfoGet(ctx Context, req TbkItemInfoGetReq) (result []TbkItemInfoGetResult, err error) {
	var resp tbkitemInfoGetResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.item.info.get"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}

// execTbkTpwdCreate 提供淘客生成淘口令接口，淘客提交口令内容、logo、url等参数，生成淘口令关键key如：￥SADadW￥，后续进行文案包装组装用于传播
func (s *Service) execTbkTpwdCreate(ctx Context, req TbkTpwdCreateReq) (result TbkTpwdCreateResult, err error) {
	var resp tbkTpwdCreateResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.tpwd.create"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}

// execTbkDgMaterialOptional 通用物料搜索API（导购）
func (s *Service) execTbkDgMaterialOptional(ctx Context, req TbkDgMaterialOptionalReq) (result []TbkDgMaterialOptionalResult, err error) {
	var resp tbkDgMaterialOptionalResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.dg.material.optional"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}

// execTbkOrderDetailsGet 淘宝客-推广者-所有订单查询
func (s *Service) execTbkOrderDetailsGet(ctx Context, req TbkOrderDetailsGetReq) (result []TbkOrderDetailsGetResult, err error) {
	var resp tbkOrderDetailsGetResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.order.details.get"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}

// execTbkScInvitecodeGet 淘宝客邀请码生成-社交
func (s *Service) execTbkScInvitecodeGet(ctx Context, req TbkScInvitecodeReq) (result TbkScInvitecodeResult, err error) {
	var resp tbkScInvitecodeGetResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.sc.invitecode.get"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}

// execTbkScPublisherInfoSave 淘宝客信息备案
func (s *Service) execTbkScPublisherInfoSave(ctx Context, req TbkScPublisherInfoSaveReq) (result TbkScPublisherInfoSaveResult, err error) {
	var resp tbkScPublisherInfoSaveResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.sc.publisher.info.save"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}

// execTbkScPublisherInfoGet 淘宝客信息查询
func (s *Service) execTbkScPublisherInfoGet(ctx Context, req TbkScPublisherInfoGetReq) (result TbkScPublisherInfoGetResult, err error) {
	var resp tbkScPublisherInfoGetResp
	if err = s.methodPost(ctx, req, &resp, "taobao.tbk.sc.publisher.info.get"); err != nil {
		return
	}
	EazyCopyStruct(resp, &result)
	return
}
