// Code generated by sdkcodegen; DO NOT EDIT.

package service

// TbkScPublisherInfoGetReq 淘宝客-公用-私域用户备案信息查询
type TbkScPublisherInfoGetReq struct {
	// InfoType 1	类型，必选 1:渠道信息；2:会员信息
	InfoType int `json:"info_type"`
	// RelationId 2323	渠道独占 - 渠道关系ID
	RelationId int64 `json:"relation_id,omitempty"`
	// PageNo 1	第几页
	PageNo int `json:"page_no,omitempty"`
	// PageSize 	10	每页大小
	PageSize int `json:"page_size,omitempty"`
	// SpecialId 1212	会员独占 - 会员运营ID
	SpecialId string `json:"special_id,omitempty"`
	// ExternalId 	12345	淘宝客外部用户标记，如自身系统账户ID；微信ID等
	ExternalId string `json:"external_id,omitempty"`
	// RelationApp common	备案的场景：common（通用备案），etao（一淘备案），minietao（一淘小程序备案），offlineShop（线下门店备案），offlinePerson（线下个人备案）。如不填默认common。查询会员信息只需填写common即可
	RelationApp string `json:"relation_app"`
}

// tbkScPublisherInfoGetResp 淘宝客-公用-私域用户备案信息查询
type tbkScPublisherInfoGetResp struct {
	TbkScPublisherInfoGetResponse tbkScPublisherInfoGetResponse `json:"tbk_sc_publisher_info_get_response"`
	*RespCommon
}

// tbkScPublisherInfoGetResponse 淘宝客-公用-私域用户备案信息查询
type tbkScPublisherInfoGetResponse struct {
	Data TbkScPublisherInfoGetResult `json:"data"`
}

// TbkScPublisherInfoGetResult 淘宝客-公用-私域用户备案信息查询
type TbkScPublisherInfoGetResult struct {
	// RootPidChannelList ["mm_1_1_1"]	渠道专属pidList
	RootPidChannelList RootPidChannelList `json:"root_pid_channel_list"`
	// TotalCount 40	共享字段 - 总记录数
	TotalCount int `json:"total_count"`
	// InviterList inviterList	共享字段 - 渠道或会员列表
	InviterList InviterList `json:"inviter_list"`
}

// RootPidChannelList 淘宝客-公用-私域用户备案信息查询
type RootPidChannelList struct {
	// String ["mm_1_1_1"]	渠道专属pidList
	String []string `json:"string"`
}

// InviterList 淘宝客-公用-私域用户备案信息查询
type InviterList struct {
	// MapData inviterList	共享字段 - 渠道或会员列表
	MapData []MapData `json:"map_data"`
}

// MapData 淘宝客-公用-私域用户备案信息查询
type MapData struct {
	// MapData inviterList	共享字段 - 渠道或会员列表
	MapData []MapData `json:"map_data"`
	// RelationApp 	common	共享字段 - 备案场景：common（通用备案），etao（一淘备案），minietao（一淘小程序备案），offlineShop（线下门店备案），offlinePerson（线下个人备案）
	RelationApp string `json:"relation_app"`
	// CreateDate 2018-06-01 11:12:23	共享字段 - 备案日期
	CreateDate Time `json:"create_date"`
	// AccountName s**x	共享字段 - 渠道/会员昵称
	AccountName string `json:"account_name"`
	// RealName xxx	共享字段 - 渠道/会员姓名
	RealName string `json:"real_name"`
	// RelationID 40232	渠道独有 - 渠道关系ID
	RelationID int `json:"relation_id"`
	// OfflineScene 	门店	渠道独有 - 线下场景信息，1 - 门店，2- 学校，3 - 工厂，4 - 其他
	OfflineScene string `json:"offline_scene"`
	// OnlineScene 微信群	渠道独有 - 线上场景信息，1 - 微信群，2- QQ群，3 - 其他
	OnlineScene string `json:"online_scene"`
	// Note 小蜜蜂	渠道独有 - 媒体侧渠道备注信息
	Note string `json:"note"`
	// RootPid mm_1_1_1	共享字段 - 渠道/会员专属pid
	RootPid string `json:"root_pid"`
	// Rtag 	123	共享字段 - 渠道/会员原始身份信息
	Rtag string `json:"rtag"`
	// OfflineInfo 	线下	线下备案专属信息
	OfflineInfo OfflineInfo `json:"offline_info"`
	// SpecialID 12345	会员独有 - 会员运营ID
	SpecialID int `json:"special_id"`
	// PunishStatus 1	渠道独有 - 处罚状态
	PunishStatus string `json:"punish_status"`
	// ExternalID 	12345	淘宝客外部用户标记，如自身系统账户ID；微信ID等
	ExternalID string `json:"external_id"`
}

// OfflineInfo 淘宝客-公用-私域用户备案信息查询
type OfflineInfo struct {
	// MapData inviterList	共享字段 - 渠道或会员列表
	MapData []MapData `json:"map_data"`
	// ShopName 日用百货店	渠道独有 -店铺名称
	ShopName string `json:"shop_name"`
	// ShopType 生活服务类 电信营业厅	渠道独有 -店铺类型
	ShopType string `json:"shop_type"`
	// PhoneNumber 	1590000000	渠道独有 -手机号码
	PhoneNumber string `json:"phone_number"`
	// DetailAddress xx街道xx号楼	渠道独有 -详细地址
	DetailAddress string `json:"detail_address"`
	// Location 	内蒙古自治区 呼和浩特市	渠道独有 -地区
	Location string `json:"location"`
	// ShopCertifyType 营业执照	渠道独有 -证件类型
	ShopCertifyType string `json:"shop_certify_type"`
	// CertifyNumber 23445677	渠道独有 -对应的证件证件类型编号
	CertifyNumber string `json:"certify_number"`
	// Career 个人 快递员	渠道独有 -经营类型
	Career string `json:"career"`
}

// TbkScPublisherInfoSaveReq 淘宝客-公用-私域用户备案
type TbkScPublisherInfoSaveReq struct {
	// RelationFrom 1	渠道备案 - 来源，取链接的来源
	RelationFrom string `json:"relation_from,omitempty"`
	// OfflineScene 	1	渠道备案 - 线下场景信息，1 - 门店，2- 学校，3 - 工厂，4 - 其他
	OfflineScene string `json:"offline_scene,omitempty"`
	// OnlineScene 1	渠道备案 - 线上场景信息，1 - 微信群，2- QQ群，3 - 其他
	OnlineScene string `json:"online_scene,omitempty"`
	// InviterCode xxx	渠道备案 - 淘宝客邀请渠道的邀请码
	InviterCode string `json:"inviter_code"`
	// InfoType 	1	类型，必选 默认为1:
	InfoType int `json:"info_type"`
	// Note 小蜜蜂	媒体侧渠道备注
	Note string `json:"note,omitempty"`
	// RegisterInfo {"phoneNumber":"18801088599","city":"江苏省","province":"南京市","location":"玄武区花园小区","detailAddress":"5号楼3单元101室","shopType":"社区店","shopName":"全家便利店","shopCertifyType":"营业执照","certifyNumber":"111100299001"}	线下备案注册信息,字段包含: 电话号码(phoneNumber，必填),省(province,必填),市(city,必填),区县街道(location,必填),详细地址(detailAddress,必填),经营类型(career,线下个人必填),店铺类型(shopType,线下店铺必填),店铺名称(shopName,线下店铺必填),店铺证书类型(shopCertifyType,线下店铺选填),店铺证书编号(certifyNumber,线下店铺选填)
	RegisterInfo RawMessage `json:"register_info,omitempty"`
}

// tbkScPublisherInfoSaveResp 淘宝客-公用-私域用户备案
type tbkScPublisherInfoSaveResp struct {
	TbkScPublisherInfoSaveResponse tbkScPublisherInfoSaveResponse `json:"tbk_sc_publisher_info_save_response"`
	*RespCommon
}

// tbkScPublisherInfoSaveResponse 淘宝客-公用-私域用户备案
type tbkScPublisherInfoSaveResponse struct {
	Data TbkScPublisherInfoSaveResult `json:"data"`
}

// TbkScPublisherInfoSaveResult 淘宝客-公用-私域用户备案
type TbkScPublisherInfoSaveResult struct {
	// RelationId 40232	渠道关系ID
	RelationId int64 `json:"relation_id"`
	// AccountName 	xxx	渠道昵称
	AccountName string `json:"account_name"`
	// SpecialId 32304	会员运营ID
	SpecialId int64 `json:"special_id"`
	// Desc 绑定成功	如果重复绑定会提示：”重复绑定渠道“或”重复绑定粉丝“
	Desc int64 `json:"string"`
}

// TbkScInvitecodeReq 淘宝客邀请码生成-社交
type TbkScInvitecodeReq struct {
	// RelationID 11	渠道关系ID
	RelationID int64 `json:"relation_id,omitempty"`
	// RelationApp common	渠道推广的物料类型
	RelationApp string `json:"relation_app"`
	// CodeType	 1	邀请码类型，1 - 渠道邀请，2 - 渠道裂变，3 -会员邀请
	CodeType int `json:"code_type"`
}

// tbkScInvitecodeGetResp 淘宝客邀请码生成-社交
type tbkScInvitecodeGetResp struct {
	ScInvitecodeGetResponse tbkScInvitecodeGetResponse `json:"tbk_sc_invitecode_get_response"`
	*RespCommon
}

// tbkScInvitecodeGetResponse 淘宝客邀请码生成-社交
type tbkScInvitecodeGetResponse struct {
	Data TbkScInvitecodeResult `json:"data"`
}

// TbkScInvitecodeResult 淘宝客邀请码生成-社交
type TbkScInvitecodeResult struct {
	// InviterCode xxxx	邀请码
	InviterCode string `json:"inviter_code"`
}

// TbkItemInfoGetReq 淘宝客商品详情查询（简版）
type TbkItemInfoGetReq struct {
	// NumIDs 商品ID串，用,分割，最大40个
	NumIDs string `json:"num_iids"`
	// Platform 链接形式：1：PC，2：无线，默认：１
	Platform int `json:"platform,omitempty"`
	// Ip	 ip地址，影响邮费获取，如果不传或者传入不准确，邮费无法精准提供
	Ip string `json:"ip,omitempty"`
}

// tbkitemInfoGetResp 淘宝客商品详情查询（简版）
type tbkitemInfoGetResp struct {
	ItemInfoGetResponse tbkitemInfoGetResponse `json:"tbk_item_info_get_response"`
	*RespCommon
}

// tbkitemInfoGetResponse 淘宝客商品详情查询（简版）
type tbkitemInfoGetResponse struct {
	Results   tbkitemInfoGetResults `json:"results"`
	RequestID string                `json:"request_id"`
}

// tbkitemInfoGetResults 淘宝客商品详情查询（简版）
type tbkitemInfoGetResults struct {
	// TbkItemInfoGetResults 淘宝客商品
	TbkItemInfoGetResults []TbkItemInfoGetResult `json:"n_tbk_item"`
}

// smallImages 淘宝客商品详情查询（简版）
type smallImages struct {
	// String 淘宝客商品
	String []string `json:"string"`
}

// TbkItemInfoGetResult 淘宝客商品详情查询（简版）
type TbkItemInfoGetResult struct {
	// CatName 	女装	一级类目名称
	CatName string `json:"cat_name"`
	// NumIid 123	商品ID
	NumIid int `json:"num_iid"`
	// Title 连衣裙	商品标题
	Title string `json:"title"`
	// PictURL http://gi4.md.alicdn.com/bao/uploaded/i4/xxx.jpg	商品主图
	PictURL string `json:"pict_url"`
	// SmallImages http://gi4.md.alicdn.com/bao/uploaded/i4/xxx.jpg	商品小图列表
	SmallImages smallImages `json:"small_images"`
	// ReservePrice 102.00	商品一口价格
	ReservePrice string `json:"reserve_price"`
	// ZkFinalPrice 	88.00	折扣价（元） 若属于预售商品，付定金时间内，折扣价=预售价
	ZkFinalPrice string `json:"zk_final_price"`
	// UserType 1	卖家类型，0表示集市，1表示商城
	UserType int `json:"user_type"`
	// Provcity 杭州	商品所在地
	Provcity string `json:"provcity"`
	// ItemURL http://detail.m.tmall.com/item.htm?id=xxx	商品链接
	ItemURL string `json:"item_url"`
	// SellerID 123	卖家id
	SellerID int `json:"seller_id"`
	// Volume 1	30天销量
	Volume int `json:"volume"`
	// Nick xx旗舰店	店铺名称
	Nick string `json:"nick"`
	// CatLeafName 情趣内衣	叶子类目名称
	CatLeafName string `json:"cat_leaf_name"`
	// IsPrepay true	是否加入消费者保障
	IsPrepay bool `json:"is_prepay"`
	// ShopDsr 23	店铺dsr 评分
	ShopDsr int `json:"shop_dsr"`
	// Ratesum 13	卖家等级
	Ratesum int `json:"ratesum"`
	// IRfdRate true	退款率是否低于行业均值
	IRfdRate bool `json:"i_rfd_rate"`
	// HGoodRate true	好评率是否高于行业均值
	HGoodRate bool `json:"h_good_rate"`
	// HPayRate30 true	成交转化是否高于行业均值
	HPayRate30 bool `json:"h_pay_rate30"`
	// FreeShipment true	是否包邮
	FreeShipment bool `json:"free_shipment"`
	// MaterialLibType 1	商品库类型，支持多库类型输出，以英文逗号分隔“,”分隔，1:营销商品主推库，2. 内容商品库，如果值为空则不属于1，2这两种商品类型
	MaterialLibType string `json:"material_lib_type"`
	// PresaleDiscountFeeText 	付定金立减20元	预售商品-商品优惠信息
	PresaleDiscountFeeText string `json:"presale_discount_fee_text"`
	// PresaleTailEndTime 1937297392332	预售商品-付定金结束时间（毫秒）
	PresaleTailEndTime int64 `json:"presale_tail_end_time"`
	// PresaleTailStartTime 1937297392332	预售商品-付尾款开始时间（毫秒）
	PresaleTailStartTime int64 `json:"presale_tail_start_time"`
	// PresaleEndTime 	1937297392332	预售商品-付定金结束时间（毫秒）
	PresaleEndTime int64 `json:"presale_end_time"`
	// PresaleStartTime 1937297392332	预售商品-付定金开始时间（毫秒）
	PresaleStartTime int64 `json:"presale_start_time"`
	// PresaleDeposit 100	预售商品-定金（元）
	PresaleDeposit string `json:"presale_deposit"`
	// JuPlayEndTime 1937297392332	聚划算满减 -结束时间（毫秒）
	JuPlayEndTime int64 `json:"ju_play_end_time"`
	// JuPlayStartTime 	1937297392332	聚划算满减 -开始时间（毫秒）
	JuPlayStartTime int64 `json:"ju_play_start_time"`
	// PlayInfo 玩法	1聚划算满减：满N件减X元，满N件X折，满N件X元） 2天猫限时抢：前N分钟每件X元，前N分钟满N件每件X元，前N件每件X元）
	PlayInfo string `json:"play_info"`
	// TmallPlayActivityEndTime 1937297392332	天猫限时抢可售 -结束时间（毫秒）
	TmallPlayActivityEndTime int64 `json:"tmall_play_activity_end_time"`
	// TmallPlayActivityStartTime 1937297392332	天猫限时抢可售 -开始时间（毫秒）
	TmallPlayActivityStartTime int64 `json:"tmall_play_activity_start_time"`
	// JuOnlineStartTime 	1581868800000	聚划算信息-聚淘开始时间（毫秒）
	JuOnlineStartTime string `json:"ju_online_start_time"`
	// JuOnlineEndTime 1582300799000	聚划算信息-聚淘结束时间（毫秒）
	JuOnlineEndTime string `json:"ju_online_end_time"`
	// JuPreShowStartTime 1581868800000	聚划算信息-商品预热开始时间（毫秒）
	JuPreShowStartTime string `json:"ju_pre_show_start_time"`
	// JuPreShowEndTime 1582300799000	聚划算信息-商品预热结束时间（毫秒）
	JuPreShowEndTime string `json:"ju_pre_show_end_time"`
	// SalePrice 168	活动价
	SalePrice string `json:"sale_price"`
	// KuadianPromotionInfo ["每100减20","每200减50"]	跨店满减信息
	KuadianPromotionInfo string `json:"kuadian_promotion_info"`
}

// CouponGetReq 阿里妈妈推广券信息查询。传入商品ID+券ID，或者传入me参数，均可查询券信息。
type CouponGetReq struct {
	// Me nfr%2BYTo2k1PX18gaNN%2BIPkIG2PadNYbBnwEsv6mRavWieOoOE3L9OdmbDSSyHbGxBAXjHpLKvZbL1320ML%2BCF5FRtW7N7yJ056Lgym4X01A%3D	带券ID与商品ID的加密串
	Me string `json:"me,omitempty"`
	// ItemID 123	商品ID
	ItemID int `json:"item_id,omitempty"`
	// ActivityID	 sdfwe3eefsdf	券ID
	ActivityID string `json:"activity_id,omitempty"`
}

// couponGetResp 淘宝客-公用-阿里妈妈推广券详情查询
type couponGetResp struct {
	TbkCouponGetResponse tbkCouponGetResponse `json:"tbk_coupon_get_response"`
	*RespCommon
}

// tbkCouponGetResponse 淘宝客-公用-阿里妈妈推广券详情查询
type tbkCouponGetResponse struct {
	Data      CouponGetResult `json:"data"`
	RequestID string          `json:"request_id"`
}

// CouponGetResult 淘宝客-公用-阿里妈妈推广券详情查询
type CouponGetResult struct {
	// CouponStartFee 	29.00	优惠券门槛金额
	CouponStartFee string `json:"coupon_start_fee"`
	// CouponRemainCount 26996	优惠券剩余量
	CouponRemainCount int `json:"coupon_remain_count"`
	// CouponTotalCount 	30000	优惠券总量
	CouponTotalCount int `json:"coupon_total_count"`
	// CouponEndTime 2017-08-17	优惠券结束时间
	CouponEndTime string `json:"coupon_end_time"`
	// CouponStartTime 	2017-08-15	优惠券开始时间
	CouponStartTime string `json:"coupon_start_time"`
	// CouponAmount 10.00	优惠券金额
	CouponAmount string `json:"coupon_amount"`
	// CouponSrcScene 	1	券类型，1 表示全网公开券，4 表示妈妈渠道券
	CouponSrcScene int `json:"coupon_src_scene"`
	// CouponType 	0	券属性，0表示店铺券，1表示单品券
	CouponType int `json:"coupon_type"`
	// CouponActivityID 	xsdss	券ID
	CouponActivityID string `json:"coupon_activity_id"`
}

// JuTqgGetReq 获取淘抢购的数据，淘客商品转淘客链接，非淘客商品输出普通链接
type JuTqgGetReq struct {
	// AdzoneID 123	推广位id（推广位申请方式：http://club.alimama.com/read.php?spm=0.0.0.0.npQdST&tid=6306396&ds=1&page=1&toread=1）
	AdzoneID int64 `json:"adzone_id"`
	// Fields click_url,pic_url,reserve_price,zk_final_price,total_amount,sold_num,title,category_name,start_time,end_time	需返回的字段列表
	Fields string `json:"fields"`
	// StartTime 2016-08-09 09:00:00	最早开团时间
	StartTime string `json:"start_time"`
	// EndTime 2016-08-09 16:00:00	最晚开团时间
	EndTime string `json:"end_time"`
}

// juTqgGetResp 淘抢购api
type juTqgGetResp struct {
	TbkJuTqgGetResponse tbkJuTqgGetResponse `json:"tbk_ju_tqg_get_response"`
}

// tbkJuTqgGetResponse 淘抢购api
type tbkJuTqgGetResponse struct {
	Results []TbkJuTqgGetResult `json:"results"`
	// TotalResults 	20	返回的结果数
	TotalResults int    `json:"total_results"`
	RequestID    string `json:"request_id"`
}

// TbkJuTqgGetResult 淘抢购api
type TbkJuTqgGetResult struct {
	// Title 连衣裙	商品标题
	Title string `json:"title"`
	// TotalAmount 100	总库存
	TotalAmount int `json:"total_amount"`
	// ClickURL http://s.click.taobao.com/t?e=x	商品链接（是淘客商品返回淘客链接，非淘客商品返回普通h5链接）
	ClickURL string `json:"click_url"`
	// CategoryName 潮流女装	类目名称
	CategoryName string `json:"category_name"`
	// ZkFinalPrice 50.00	淘抢购活动价
	ZkFinalPrice string `json:"zk_final_price"`
	// EndTime 	2016-08-09 13:00:00	结束时间
	EndTime string `json:"end_time"`
	// SoldNum 50	已抢购数量
	SoldNum int `json:"sold_num"`
	// StartTime 	2016-08-09 12:00:00	开团时间
	StartTime string `json:"start_time"`
	// ReservePrice 	100.00	商品原价
	ReservePrice string `json:"reserve_price"`
	// PicURL http: //img4.tbcdn.cn/tfscom/i4/189490253156622336/TB2bZuSsVXXXXcNXXXXXXXXXXXX_!!0-juitemmedia.jpg	商品主图
	PicURL string `json:"pic_url"`
	// NumIid 123	商品ID
	NumIid int `json:"num_iid"`
}

// TbkTpwdCreateReq 提供淘客生成淘口令接口，淘客提交口令内容、logo、url等参数，生成淘口令关键key如：￥SADadW￥，后续进行文案包装组装用于传播
type TbkTpwdCreateReq struct {
	// UserID 123	生成口令的淘宝用户ID
	UserID string `json:"user_id,omitempty"`
	// Text 长度大于5个字符	口令弹框内容
	Text string `json:"text"`
	// URL https://uland.taobao.com/	口令跳转目标页
	URL string `json:"url"`
	// Logo 	https://uland.taobao.com/	口令弹框logoURL
	Logo string `json:"logo,omitempty"`
	// Ext	 	{}	扩展字段JSON格式
	Ext string `json:"ext,omitempty"`
}

// tbkTpwdCreateResp 淘宝客-公用-淘口令生成
type tbkTpwdCreateResp struct {
	TbkTpwdCreateResponse tbkTpwdCreateResponse `json:"tbk_tpwd_create_response"`
	*RespCommon
}

// tbkTpwdCreateResponse 淘宝客-公用-淘口令生成
type tbkTpwdCreateResponse struct {
	Data      TbkTpwdCreateResult `json:"data"`
	RequestID string              `json:"request_id"`
}

// TbkTpwdCreateResult 淘宝客-公用-淘口令生成
type TbkTpwdCreateResult struct {
	// Model ￥AADPOKFz￥	password
	Model string `json:"model"`
}

// ItemClickExtractReq 从长链接或短链接中解析出open_iid
type ItemClickExtractReq struct {
	// ClickURL	 https://s.click.taobao.com/***	长链接或短链接
	ClickURL string `json:"click_url	"`
}

// itemClickExtractResp 淘宝客-公用-链接解析出商品id
type itemClickExtractResp struct {
	TbkItemClickExtractResponse TbkItemClickExtractResult `json:"tbk_item_click_extract_response	"`
	*RespCommon
}

// TbkItemClickExtractResult 淘宝客-公用-链接解析出商品id
type TbkItemClickExtractResult struct {
	// ItemID	 	123	商品id
	ItemID string `json:"item_id	"`
	// OpenIid	 xxxxx	商品混淆id
	OpenIid string `json:"open_iid	"`
}

// TbkDgMaterialOptionalReq 淘宝客-推广者-物料搜索
type TbkDgMaterialOptionalReq struct {
	// StartDsr 10 商品筛选(特定媒体支持)-店铺dsr评分。筛选大于等于当前设置的店铺dsr评分的商品0-50000之间
	StartDsr int `json:"start_dsr,omitempty"`
	// PageSize 20 页大小，默认20，1~100
	PageSize int `json:"page_size,omitempty"`
	// PageNo 1 第几页，默认：１
	PageNo int `json:"page_no,omitempty"`
	// Platform 1  链接形式：1：PC，2：无线，默认：１
	Platform int `json:"platform,omitempty"`
	// EndTkRate 1234 商品筛选-淘客佣金比率上限。如：1234表示12.34%
	EndTkRate int `json:"end_tk_rate,omitempty"`
	// StartTkRate 1234 商品筛选-淘客佣金比率下限。如：1234表示12.34%
	StartTkRate int `json:"start_tk_rate,omitempty"`
	// EndPrice 10   商品筛选-折扣价范围上限。单位：元
	EndPrice int `json:"end_price,omitempty"`
	// StartPrice 10   商品筛选-折扣价范围下限。单位：元
	StartPrice int `json:"start_price,omitempty"`
	// IsOverseas false    商品筛选-是否海外商品。true表示属于海外商品，false或不设置表示不限
	IsOverseas bool `json:"is_overseas,omitempty"`
	// IsTmall false    商品筛选-是否天猫商品。true表示属于天猫商品，false或不设置表示不限
	IsTmall bool `json:"is_tmall,omitempty"`
	// Sort tk_rate_des  排序_des（降序），排序_asc（升序），销量（total_sales），淘客佣金比率（tk_rate）， 累计推广量（tk_total_sales），总支出佣金（tk_total_commi），价格（price）
	Sort string `json:"sort,omitempty"`
	// Itemloc 杭州   商品筛选-所在地
	Itemloc string `json:"itemloc,omitempty"`
	// Cat 16,18    商品筛选-后台类目ID。用,分割，最大10个，该ID可以通过taobao.itemcats.get接口获取到
	Cat string `json:"cat,omitempty"`
	// Q 女装   商品筛选-查询词
	Q string `json:"q,omitempty"`
	// MaterialId 2836 不传时默认物料id=2836；如果直接对消费者投放，可使用官方个性化算法优化的搜索物料id=17004
	MaterialId int `json:"material_id,omitempty"`
	// HasCoupon false    优惠券筛选-是否有优惠券。true表示该商品有优惠券，false或不设置表示不限
	HasCoupon bool `json:"has_coupon,omitempty"`
	// Ip 13.2.33.4    ip参数影响邮费获取，如果不传或者传入不准确，邮费无法精准提供
	Ip string `json:"ip,omitempty"`
	// AdzoneId 12345678 mm_xxx_xxx_12345678三段式的最后一段数字
	AdzoneId int `json:"adzone_id"`
	// NeedFreeShipment true 商品筛选-是否包邮。true表示包邮，false或不设置表示不限
	NeedFreeShipment bool `json:"need_free_shipment,omitempty"`
	// NeedPrepay true 商品筛选-是否加入消费者保障。true表示加入，false或不设置表示不限
	NeedPrepay bool `json:"need_prepay,omitempty"`
	// IncludePayRate30 true 商品筛选(特定媒体支持)-成交转化是否高于行业均值。True表示大于等于，false或不设置表示不限
	IncludePayRate30 bool `json:"include_pay_rate_30,omitempty"`
	// IncludeGoodRate true 商品筛选-好评率是否高于行业均值。True表示大于等于，false或不设置表示不限
	IncludeGoodRate bool `json:"include_good_rate,omitempty"`
	// IncludeRfdRate true 商品筛选(特定媒体支持)-退款率是否低于行业均值。True表示大于等于，false或不设置表示不限
	IncludeRfdRate bool `json:"include_rfd_rate,omitempty"`
	// NpxLevel 2    商品筛选-牛皮癣程度。取值：1不限，2无，3轻微
	NpxLevel int `json:"npx_level,omitempty"`
	// EndKaTkRate 1234 商品筛选-KA媒体淘客佣金比率上限。如：1234表示12.34%
	EndKaTkRate int `json:"end_ka_tk_rate,omitempty"`
	// StartKaTkRate 1234 商品筛选-KA媒体淘客佣金比率下限。如：1234表示12.34%
	StartKaTkRate int `json:"start_ka_tk_rate,omitempty"`
	// DeviceEncrypt MD5  智能匹配-设备号加密类型：MD5
	DeviceEncrypt string `json:"device_encrypt,omitempty"`
	// DeviceValue xxx  智能匹配-设备号加密后的值（MD5加密需32位小写）
	DeviceValue string `json:"device_value,omitempty"`
	// DeviceType IMEI 智能匹配-设备号类型：IMEI，或者IDFA，或者UTDID（UTDID不支持MD5加密），或者OAID
	DeviceType string `json:"device_type,omitempty"`
	// LockRateEndTime 1567440000000    锁佣结束时间
	LockRateEndTime int64 `json:"lock_rate_end_time,omitempty"`
	// LockRateStartTime 1567440000000    锁佣开始时间
	LockRateStartTime int64 `json:"lock_rate_start_time,omitempty"`
	// Longitude 121.473701   本地化业务入参-LBS信息-经度
	Longitude string `json:"longitude,omitempty"`
	// Latitude 31.230370    本地化业务入参-LBS信息-纬度
	Latitude string `json:"latitude,omitempty"`
	// CityCode 310000   本地化业务入参-LBS信息-国标城市码，仅支持单个请求，请求饿了么卡券物料时，该字段必填。 （详细城市ID见：https://mo.m.taobao.com/page_2020010315120200508）
	CityCode string `json:"city_code,omitempty"`
	// SellerIds 1,2,3,4  商家id，仅支持饿了么卡券商家ID，支持批量请求1-100以内，多个商家ID使用英文逗号分隔
	SellerIds string `json:"seller_ids,omitempty"`
}

// tbkDgMaterialOptionalResp 淘宝客-推广者-物料搜索
type tbkDgMaterialOptionalResp struct {
	TbkDgMaterialOptionalResponse tbkDgMaterialOptionalResponse `json:"tbk_dg_material_optional_response"`
	*RespCommon
}

// tbkDgMaterialOptionalResponse 淘宝客-推广者-物料搜索
type tbkDgMaterialOptionalResponse struct {
	// TotalResults 1212	搜索到符合条件的结果总数
	TotalResults int                          `json:"total_results"`
	ResultList   tbkDgMaterialOptionalResults `json:"result_list"`
	RequestID    string                       `json:"request_id"`
}

// tbkDgMaterialOptionalResults 淘宝客-推广者-物料搜索
type tbkDgMaterialOptionalResults struct {
	MapData []TbkDgMaterialOptionalResult `json:"map_data"`
}

// TbkDgMaterialOptionalResult 淘宝客-推广者-物料搜索
type TbkDgMaterialOptionalResult struct {
	// CouponStartTime 2017-10-29	优惠券信息-优惠券开始时间
	CouponStartTime string `json:"coupon_start_time"`
	// CouponEndTime 2017-10-29	优惠券信息-优惠券结束时间
	CouponEndTime string `json:"coupon_end_time"`
	// InfoDxjh {"19013551":"2850","74510538":"2550"}	商品信息-定向计划信息
	InfoDxjh RawMessage `json:"info_dxjh"`
	// TkTotalSales 11	商品信息-淘客30天推广量
	TkTotalSales string `json:"tk_total_sales"`
	// TkTotalCommi 323	商品信息-月支出佣金(该字段废弃，请勿再用)
	TkTotalCommi string `json:"tk_total_commi"`
	// CouponID d62db1ab8d9546b1bf0ff49bda5fc33b	优惠券信息-优惠券id
	CouponID string `json:"coupon_id"`
	// NumIid 556633720749	商品信息-宝贝id(该字段废弃，请勿再用)
	NumIid int64 `json:"num_iid"`
	// Title 毛呢阔腿裤港味复古女裤子秋冬九分裤萝卜裤显瘦高腰韩版2017新款	商品信息-商品标题
	Title string `json:"title"`
	// PictURL https://img.alicdn.com/bao/uploaded/i4/745957850/TB1WzSRmV9gSKJjSspbXXbeNXXa_!!0-item_pic.jpg	商品信息-商品主图
	PictURL string `json:"pict_url"`
	// SmallImages https://img.alicdn.com/i4/3077291146/TB2NA3poDnI8KJjSszgXXc8ApXa_!!3077291146.jpg	商品信息-商品小图列表
	SmallImages smallImages `json:"small_images"`
	// ReservePrice 102.00	商品信息-商品一口价格
	ReservePrice string `json:"reserve_price"`
	// ZkFinalPrice 88.00	折扣价（元） 若属于预售商品，付定金时间内，折扣价=预售价
	ZkFinalPrice string `json:"zk_final_price"`
	// UserType 1	店铺信息-卖家类型。0表示集市，1表示天猫
	UserType int `json:"user_type"`
	// Provcity 杭州	商品信息-宝贝所在地
	Provcity string `json:"provcity"`
	// ItemURL https://item.taobao.com/item.htm?id=564591813536	链接-宝贝地址
	ItemURL string `json:"item_url"`
	// IncludeMkt false	商品信息-是否包含营销计划
	IncludeMkt string `json:"include_mkt"`
	// IncludeDxjh false	商品信息-是否包含定向计划
	IncludeDxjh string `json:"include_dxjh"`
	// CommissionRate 1550表示15.5%	商品信息-佣金比率。1550表示15.5%
	CommissionRate string `json:"commission_rate"`
	// Volume 123	商品信息-30天销量（饿了么卡券信息-总销量）
	Volume int `json:"volume"`
	// SellerID 232332	店铺信息-卖家id
	SellerID int `json:"seller_id"`
	// CouponTotalCount 22323	优惠券信息-优惠券总量
	CouponTotalCount int `json:"coupon_total_count"`
	// CouponRemainCount 111	优惠券信息-优惠券剩余量
	CouponRemainCount int `json:"coupon_remain_count"`
	// CouponInfo 满299元减20元	优惠券信息-优惠券满减信息
	CouponInfo string `json:"coupon_info"`
	// CommissionType MKT表示营销计划，SP表示定向计划，COMMON表示通用计划	商品信息-佣金类型。MKT表示营销计划，SP表示定向计划，COMMON表示通用计划
	CommissionType string `json:"commission_type"`
	// ShopTitle xx旗舰店	店铺信息-店铺名称
	ShopTitle string `json:"shop_title"`
	// ShopDsr 13	店铺信息-店铺dsr评分
	ShopDsr int `json:"shop_dsr"`
	// CouponShareURL uland.xxx	链接-宝贝+券二合一页面链接
	CouponShareURL string `json:"coupon_share_url"`
	// URL s.click.xxx	链接-宝贝推广链接
	URL string `json:"url"`
	// LevelOneCategoryName 女装	商品信息-一级类目名称
	LevelOneCategoryName string `json:"level_one_category_name"`
	// LevelOneCategoryID 20	商品信息-一级类目ID
	LevelOneCategoryID int `json:"level_one_category_id"`
	// CategoryName 连衣裙	商品信息-叶子类目名称
	CategoryName string `json:"category_name"`
	// CategoryID 162201	商品信息-叶子类目id
	CategoryID int `json:"category_id"`
	// ShortTitle xxsd	商品信息-商品短标题
	ShortTitle string `json:"short_title"`
	// WhiteImage https://img.alicdn.com/bao/uploaded/i4/745957850/TB1WzSRmV9gSKJjSspbXXbeNXXa_!!0-item_pic.jpg	商品信息-商品白底图
	WhiteImage string `json:"white_image"`
	// Oetime 2018-08-21 11:23:43	拼团专用-拼团结束时间
	Oetime string `json:"oetime"`
	// Ostime 2018-08-21 11:23:43	拼团专用-拼团开始时间
	Ostime string `json:"ostime"`
	// JddNum 10	拼团专用-拼团几人团
	JddNum int `json:"jdd_num"`
	// JddPrice 5	拼团专用-拼团拼成价，单位元
	JddPrice string `json:"jdd_price"`
	// UvSumPreSale 23	预售专用-预售数量
	UvSumPreSale int `json:"uv_sum_pre_sale"`
	// XID uESS0mv8JvfJRMKlIgCD5At9VuHVBXoqBRihfQlo4ybLiKygRlqiN4eoxoZDfe38uSogWy6GB971jD2N8tLuuc	链接-物料块id(测试中请勿使用)
	XID string `json:"x_id"`
	// CouponStartFee 29.00	优惠券信息-优惠券起用门槛，满X元可用。如：满299元减20元
	CouponStartFee string `json:"coupon_start_fee"`
	// CouponAmount 10.00	优惠券（元） 若属于预售商品，该优惠券付尾款可用，付定金不可用
	CouponAmount string `json:"coupon_amount"`
	// ItemDescription 季凉被 全棉亲肤	商品信息-宝贝描述(推荐理由)
	ItemDescription string `json:"item_description"`
	// Nick 旗舰店	店铺信息-卖家昵称
	Nick string `json:"nick"`
	// OrigPrice 25	拼团专用-拼团一人价（原价)，单位元
	OrigPrice string `json:"orig_price"`
	// TotalStock 5555	拼团专用-拼团库存数量
	TotalStock int `json:"total_stock"`
	// SellNum 1111	拼团专用-拼团已售数量
	SellNum int `json:"sell_num"`
	// Stock 4444	拼团专用-拼团剩余库存
	Stock int `json:"stock"`
	// TmallPlayActivityInfo 前n件x折	营销-天猫营销玩法
	TmallPlayActivityInfo string `json:"tmall_play_activity_info"`
	// ItemID 5678899993	商品信息-宝贝id
	ItemID int64 `json:"item_id"`
	// RealPostFee 0.00	商品邮费
	RealPostFee string `json:"real_post_fee"`
	// LockRate 1567440000000	锁住的佣金率
	LockRate string `json:"lock_rate"`
	// LockRateEndTime 1567440000000	锁佣结束时间
	LockRateEndTime int64 `json:"lock_rate_end_time"`
	// LockRateStartTime 1567440000000	锁佣开始时间
	LockRateStartTime int64 `json:"lock_rate_start_time"`
	// PresaleDiscountFeeText 付定金立减5元	预售商品-优惠
	PresaleDiscountFeeText string `json:"presale_discount_fee_text"`
	// PresaleTailEndTime 1567440000000	预售商品-付尾款结束时间（毫秒）
	PresaleTailEndTime int64 `json:"presale_tail_end_time"`
	// PresaleTailStartTime 1567440000000	预售商品-付尾款开始时间（毫秒）
	PresaleTailStartTime int64 `json:"presale_tail_start_time"`
	// PresaleEndTime 	1567440000000	预售商品-付定金结束时间（毫秒）
	PresaleEndTime int64 `json:"presale_end_time"`
	// PresaleStartTime 1567440000000	预售商品-付定金开始时间（毫秒）
	PresaleStartTime int64 `json:"presale_start_time"`
	// PresaleDeposit 100	预售商品-定金（元）
	PresaleDeposit string `json:"presale_deposit"`
	// YsylTljSendTime 2019-11-10 21:59:59	预售有礼-淘礼金发放时间
	YsylTljSendTime string `json:"ysyl_tlj_send_time"`
	// YsylCommissionRate 2030（表示20.3%）	预售有礼-佣金比例（ 预售有礼活动享受的推广佣金比例，注：推广该活动有特殊分成规则，请详见：https://tbk.bbs.taobao.com/detail.html?appId=45301&postId=9334376 ）
	YsylCommissionRate string `json:"ysyl_commission_rate"`
	// YsylTljFace 0.6	预售有礼-预估淘礼金（元）
	YsylTljFace string `json:"ysyl_tlj_face"`
	// YsylClickURL https://uland.taobao.com/coupon/edetail?e=nqUNB1NOF3Bt3vqbdXnGloankzPYmeEFkgNrw6YHQf9pZTj41Orn8MwBAs06HAOzqQomYNedOiHDYPmqkFXqLR0HgBdG%2FDDL%2F1M%2FBw7Sf%2FesGXLf%2BqX4cbeC%2F2cR0p0NlWH0%2BknxpnCJJP%2FQkZSsyo1HvKjXo4uz&pid=mm_26381042_12970066_52864659&af=1	预售有礼-推广链接
	YsylClickURL string `json:"ysyl_click_url"`
	// YsylTljUseEndTime 2019-11-10 21:59:59	预售有礼-淘礼金使用结束时间
	YsylTljUseEndTime string `json:"ysyl_tlj_use_end_time"`
	// YsylTljUseStartTime 2019-11-10 21:59:59	预售有礼-淘礼金使用开始时间
	YsylTljUseStartTime string `json:"ysyl_tlj_use_start_time"`
	// SaleBeginTime 1567440000000	本地化-销售开始时间
	SaleBeginTime string `json:"sale_begin_time"`
	// SaleEndTime 1567440000000	本地化-销售结束时间
	SaleEndTime string `json:"sale_end_time"`
	// Distance 300	本地化-到门店距离（米）
	Distance string `json:"distance"`
	// UsableShopID 10001	本地化-可用店铺id
	UsableShopID string `json:"usable_shop_id"`
	// UsableShopName 	饿了么卡券专营店	本地化-可用店铺名称
	UsableShopName string `json:"usable_shop_name"`
	// SalePrice 168	活动价
	SalePrice string `json:"sale_price"`
	// KuadianPromotionInfo ["每100减20","每200减50"]	跨店满减信息
	KuadianPromotionInfo string `json:"kuadian_promotion_info"`
}

// TbkOrderDetailsGetReq 淘宝客-推广者-所有订单查询
type TbkOrderDetailsGetReq struct {
	// QueryType 1 查询时间类型，1：按照订单淘客创建时间查询，2:按照订单淘客付款时间查询，3:按照订单淘客结算时间查询
	QueryType int `json:"query_type,omitempty"`
	// PositionIndex 	2222_334666	位点，除第一页之外，都需要传递；前端原样返回。
	PositionIndex string `json:"position_index,omitempty"`
	// PageSize	 20	页大小，默认20，1~100
	PageSize int `json:"page_size,omitempty"`
	// MemberType 2	推广者角色类型,2:二方，3:三方，不传，表示所有角色
	MemberType int `json:"member_type,omitempty"`
	// TkStatus 	12	淘客订单状态，12-付款，13-关闭，14-确认收货，3-结算成功;不传，表示所有状态
	TkStatus int `json:"tk_status,omitempty"`
	// EndTime	 2019-04-23 12:28:22	订单查询结束时间，订单开始时间至订单结束时间，中间时间段日常要求不超过3个小时，但如618、双11、年货节等大促期间预估时间段不可超过20分钟，超过会提示错误，调用时请务必注意时间段的选择，以保证亲能正常调用！
	EndTime Time `json:"end_time"`
	// StartTime 2019-04-05 12:18:22	订单查询开始时间
	StartTime Time `json:"start_time"`
	// JumpType	 1	跳转类型，当向前或者向后翻页必须提供,-1: 向前翻页,1：向后翻页
	JumpType int `json:"jump_type,omitempty"`
	// PageNo 	1	第几页，默认1，1~100
	PageNo int `json:"page_no,omitempty"`
	// OrderScene 	1	场景订单场景类型，1:常规订单，2:渠道订单，3:会员运营订单，默认为1
	OrderScene int `json:"order_scene,omitempty"`
}

// tbkOrderDetailsGetResp 淘宝客-推广者-所有订单查询
type tbkOrderDetailsGetResp struct {
	TbkOrderDetailsGetResponse tbkOrderDetailsGetResponse `json:"tbk_order_details_get_response"`
	*RespCommon
}

// tbkOrderDetailsGetResponse 淘宝客-推广者-所有订单查询
type tbkOrderDetailsGetResponse struct {
	Data      tbkOrderDetailsGetData `json:"data"`
	RequestID string                 `json:"request_id"`
}

// tbkOrderDetailsGetData 淘宝客-推广者-所有订单查询
type tbkOrderDetailsGetData struct {
	Results tbkOrderDetailsGetResults `json:"results"`
	// HasPre false	是否还有上一页
	HasPre bool `json:"has_pre"`
	// PositionIndex 1555904214_lGltNdNvSX2
	PositionIndex string `json:"position_index"`
	HasNext       bool   `json:"has_next"`
	// PageNo 1	页码
	PageNo int `json:"page_no"`
	// PageSize 11	页大小
	PageSize int `json:"page_size"`
}

// tbkOrderDetailsGetResults 淘宝客-推广者-所有订单查询
type tbkOrderDetailsGetResults struct {
	TbkOrderDetailsGetResults []TbkOrderDetailsGetResult `json:"publisher_order_dto"`
}

// ServiceFeeDtoList 淘宝客-推广者-所有订单查询
type ServiceFeeDtoList struct {
	ServiceFeeDto []ServiceFeeDto `json:"service_fee_dto"`
}

// ServiceFeeDto 淘宝客-推广者-所有订单查询
type ServiceFeeDto struct {
	// ShareRelativeRate 	0.10	专项服务费率
	ShareRelativeRate string `json:"share_relative_rate"`
	// ShareFee 	11.11	结算专项服务费
	ShareFee string `json:"share_fee"`
	// SharePreFee 11.11	预估专项服务费
	SharePreFee string `json:"share_pre_fee"`
	// TkShareRoleType 	122	专项服务费来源，122-渠道
	TkShareRoleType int `json:"tk_share_role_type"`
}

// TbkOrderDetailsGetResult 淘宝客-推广者-所有订单查询
type TbkOrderDetailsGetResult struct {
	// TbPaidTime 2019-04-22 15:15:05	订单在淘宝拍下付款的时间
	TbPaidTime string `json:"tb_paid_time"`
	// TkPaidTime 2019-04-22 15:15:05	订单付款的时间，该时间同步淘宝，可能会略晚于买家在淘宝的订单创建时间
	TkPaidTime string `json:"tk_paid_time"`
	// PayPrice 9.11	买家确认收货的付款金额（不包含运费金额）
	PayPrice string `json:"pay_price"`
	// PubShareFee 0 结算预估收入=结算金额*提成。以买家确认收货的付款金额为基数，预估您可能获得的收入。因买家退款、您违规推广等原因，可能与您最终收入不一致。最终收入以月结后您实际收到的为准
	PubShareFee string `json:"pub_share_fee"`
	// TradeID 294159887445064307	买家通过购物车购买的每个商品对应的订单编号，此订单编号并未在淘宝买家后台透出
	TradeID string `json:"trade_id"`
	// TkOrderRole 	2	二方：佣金收益的第一归属者； 三方：从其他淘宝客佣金中进行分成的推广者
	TkOrderRole int `json:"tk_order_role"`
	// TkEarningTime 2019-04-22 15:15:05	订单确认收货后且商家完成佣金支付的时间
	TkEarningTime string `json:"tk_earning_time"`
	// AdzoneID 11	推广位管理下的推广位名称对应的ID，同时也是pid=mm_1_2_3中的“3”这段数字
	AdzoneID int64 `json:"adzone_id"`
	// PubShareRate 100	从结算佣金中分得的收益比率
	PubShareRate string `json:"pub_share_rate"`
	// Unid 11	unid
	Unid string `json:"unid"`
	// RefundTag 	0	维权标签，0 含义为非维权 1 含义为维权订单
	RefundTag int `json:"refund_tag"`
	// SubsidyRate 0	平台给与的补贴比率，如天猫、淘宝、聚划算等
	SubsidyRate string `json:"subsidy_rate"`
	// TkTotalRate 	9.99	提成=收入比率*分成比率。指实际获得收益的比率
	TkTotalRate string `json:"tk_total_rate"`
	// ItemCategoryName 淘小铺	商品所属的根类目，即一级类目的名称
	ItemCategoryName string `json:"item_category_name"`
	// SellerNick --	掌柜旺旺
	SellerNick string `json:"seller_nick"`
	// PubID 	98836808	推广者的会员id
	PubID int64 `json:"pub_id"`
	// AlimamaRate 0	推广者赚取佣金后支付给阿里妈妈的技术服务费用的比率
	AlimamaRate string `json:"alimama_rate"`
	// SubsidyType 	平台出资方，如天猫、淘宝、或聚划算等
	SubsidyType string `json:"subsidy_type"`
	// ItemImg img.alicdn.com/bao/uploaded/i1/2200782262419/O1CN01b5qlop1TjwarUo8fo_!!2200782262419.jpg	商品图片
	ItemImg string `json:"item_img"`
	// PubSharePreFee 0	付款预估收入=付款金额*提成。指买家付款金额为基数，预估您可能获得的收入。因买家退款等原因，可能与结算预估收入不一致
	PubSharePreFee string `json:"pub_share_pre_fee"`
	// AlipayTotalPrice 11.22	买家拍下付款的金额（不包含运费金额）
	AlipayTotalPrice string `json:"alipay_total_price"`
	// ItemTitle tsh_rj_测试请不要拍_阶佣11.1	商品标题
	ItemTitle string `json:"item_title"`
	// SiteName 	合伙人	媒体管理下的对应ID的自定义名称
	SiteName string `json:"site_name"`
	// ItemNum 2	商品数量
	ItemNum int `json:"item_num"`
	// SubsidyFee 	0	补贴金额=结算金额*补贴比率
	SubsidyFee string `json:"subsidy_fee"`
	// AlimamaShareFee 0	技术服务费=结算金额*收入比率*技术服务费率。推广者赚取佣金后支付给阿里妈妈的技术服务费用
	AlimamaShareFee string `json:"alimama_share_fee"`
	// TradeParentID 294159887445064307	买家在淘宝后台显示的订单编号
	TradeParentID string `json:"trade_parent_id"`
	// OrderType 如意淘	订单所属平台类型，包括天猫、淘宝、聚划算等
	OrderType string `json:"order_type"`
	// TkCreateTime 2019-04-22 15:15:05	订单创建的时间，该时间同步淘宝，可能会略晚于买家在淘宝的订单创建时间
	TkCreateTime string `json:"tk_create_time"`
	// FlowSource 	--	产品类型
	FlowSource string `json:"flow_source"`
	// TerminalType 无线	成交平台
	TerminalType string `json:"terminal_type"`
	// ClickTime 2019-04-22 15:14:55	通过推广链接达到商品、店铺详情页的点击时间
	ClickTime Time `json:"click_time"`
	// TkStatus 13	已付款：指订单已付款，但还未确认收货 已收货：指订单已确认收货，但商家佣金未支付 已结算：指订单已确认收货，且商家佣金已支付成功 已失效：指订单关闭/订单佣金小于0.01元，订单关闭主有：1）买家超时未付款； 2）买家付款前，买家/卖家取消了订付款后发起售中退款成功；3：订单结算，12：订单付款， 13订单失效，14：订单成功
	TkStatus int `json:"tk_status"`
	// ItemPrice 2.1	商品单价
	ItemPrice string `json:"item_price"`
	// ItemID 590141576510	商品id
	ItemID int64 `json:"item_id"`
	// AdzoneName 	推广位管理下的自定义推广位名称
	AdzoneName string `json:"adzone_name"`
	// TotalCommissionRate 9.99	佣金比率
	TotalCommissionRate string `json:"total_commission_rate"`
	// ItemLink 		商品链接
	ItemLink string `json:"item_link"`
	// SiteID 45598009	媒体管理下的ID，同时也是pid=mm_1_2_3中的“2”这段数字
	SiteID int `json:"site_id"`
	// SellerShopTitle --	店铺名称
	SellerShopTitle string `json:"seller_shop_title"`
	// IncomeRate 9.99	订单结算的佣金比率+平台的补贴比率
	IncomeRate string `json:"income_rate"`
	// TotalCommissionFee 0	佣金金额=结算金额*佣金比率
	TotalCommissionFee string `json:"total_commission_fee"`
	// TkCommissionPreFeeForMediaPlatform 1.05	预估内容专项服务费：内容场景专项技术服务费，内容推广者在内容场景进行推广需要支付给阿里妈妈专项的技术服务费用。专项服务费＝付款金额＊专项服务费率。
	TkCommissionPreFeeForMediaPlatform string `json:"tk_commission_pre_fee_for_media_platform"`
	// TkCommissionFeeForMediaPlatform 1.05	结算内容专项服务费：内容场景专项技术服务费，内容推广者在内容场景进行推广需要支付给阿里妈妈专项的技术服务费用。专项服务费＝结算金额＊专项服务费率。
	TkCommissionFeeForMediaPlatform string `json:"tk_commission_fee_for_media_platform"`
	// TkCommissionRateForMediaPlatform 0.01	内容专项服务费率：内容场景专项技术服务费率，内容推广者在内容场景进行推广需要按结算金额支付一定比例给阿里妈妈作为内容场景专项技术服务费，用于提供与内容平台实现产品技术对接等服务。
	TkCommissionRateForMediaPlatform string `json:"tk_commission_rate_for_media_platform"`
	// SpecialID 	21321	会员运营id
	SpecialID int64 `json:"special_id"`
	// RelationID 123123	渠道关系id
	RelationID int64 `json:"relation_id"`
	// TkDepositTime 22.32	预售时期，用户对预售商品支付的定金金额
	TkDepositTime string `json:"tk_deposit_time"`
	// TbDepositTime 	2019-09-09 12:01:01	预售时期，用户对预售商品支付定金的付款时间
	TbDepositTime string `json:"tb_deposit_time"`
	// DepositPrice 应该是预售金额
	DepositPrice string `json:"deposit_price"`
	AppKey       string `json:"app_key"`
	// AlscID 32434	口碑子订单号
	AlscID string `json:"alsc_id"`
	// AlscPid 	3434	口碑父订单号
	AlscPid string `json:"alsc_pid"`
	// ServiceFeeDtoList 	服务费信息
	ServiceFeeDtoList ServiceFeeDtoList `json:"service_fee_dto_list"`
}
