// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

import (
	"taobaoke/internal/dao"
)

// Injectors from wire.go:

func newTestService() (*Service, func(), error) {
	logger, cleanup, err := NewLogger()
	if err != nil {
		return nil, nil, err
	}
	clusterClient, cleanup2, err := dao.NewRedis()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	memcache, cleanup3, err := dao.NewMC()
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	db, cleanup4, err := dao.NewDB()
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup5, err := dao.NewMongo()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	orderClient, err := dao.NewOrderClient(client, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	daoDao, cleanup6, err := dao.New(logger, clusterClient, memcache, db, client, orderClient)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	blademasterClient, cleanup7, err := NewBmClient()
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serviceTbkMetrics, err := NewMetrics()
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serviceOrders := NewOrders(daoDao, logger, serviceTbkMetrics)
	service, cleanup8, err := New(daoDao, logger, blademasterClient, serviceOrders)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return service, func() {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
