
# This is a TOML document. Boom~
demoExpire = "24h"
uri = "http://xxx/rest"

appKey = "30055875"
# 第一个id最好别动
adzoneID =  [1,2,3,4]
taokoulingAppKey = ""
appSecret=""
session = ""
serverAddr = "https://xxx"